steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wardenhub/wardenhub-apf', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wardenhub/wardenhub-apf']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'wardenhub-apf', '--image', 'gcr.io/wardenhub/wardenhub-apf', '--region', '[REGION]', '--platform', 'managed', '--allow-unauthenticated']
images:
       - gcr.io/wardenhub/wardenhub-apf
